
app:
  urlOAuth2: https://digital.iservices.rte-france.com/token/oauth/
  urlEcowatt: https://digital.iservices.rte-france.com/open_api/ecowatt/v4/sandbox/signals
  #urlEcowatt: https://digital.iservices.rte-france.com/open_api/ecowatt/v4/signals
  secretKey:
  file: data/lastcall.json
  dureeCache: 1m
  cronRechargement: '0 15 * * * *'

logging:
  level:
#    reactor.netty.http.client: DEBUG
    #reactor.netty.http.client: TRACE
#    root: DEBUG
    org.ecowatt.dashboard: DEBUG


