
app:
  urlOAuth2: https://digital.iservices.rte-france.com/token/oauth/
  urlEcowatt: https://digital.iservices.rte-france.com/open_api/ecowatt/v4/sandbox/signals
  #urlEcowatt: https://digital.iservices.rte-france.com/open_api/ecowatt/v4/signals
  secretKey:
  path: ./data
  filename: lastcall.json
  dureeCache: 1m
  cronRechargement: '0 15 * * * *'
#  vfs4jProperties:
    #vfs.plugins.plugins1.class: io.github.abarhub.vfs.core.plugin.audit.VFS4JAuditPluginsFactory
    #vfs.plugins.plugins1.operations: COMMAND

logging:
  level:
#    reactor.netty.http.client: DEBUG
    #reactor.netty.http.client: TRACE
#    root: DEBUG
    org.ecowatt.dashboard: DEBUG

management.endpoints.web.exposure.include: health,info,prometheus

