
app:
  urlOAuth2:
  urlEcowatt:
  secretKey:
  file:
  dureeCache:
  cronRechargement:
#
#spring.security.oauth2.client:
#      registration:
#        ecowatt:
#          #authorization-grant-type: client_credentials
#          authorization-grant-type: password
#          client-id: ecowatt
#          client-secret: ${app.secretKey}
#          provider: ecowatt
#      provider:
#        ecowatt.token-uri: ${app.urlOAuth2}

#security.ignored: /**
#spring.security.enabled: false
#management.security.enabled: false
#security.basic.enabled: false

