
app:
  urlOAuth2:
  urlEcowatt:
  secretKey:
  path:
  filename:
  dureeCache:
  cronRechargement:
  vfs4j.properties:

#security.ignored: /**
#spring.security.enabled: false
#management.security.enabled: false
#security.basic.enabled: false


